#created by Angelo Tapullima @anked
#flutter version 1.26.0-17.8.pre -- fvm

#la llave de android esta en /key.jks
#la configuración de la llave esta en /android/key.properties



name: enchiladasapp
description: A new Flutter application.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  font_awesome_flutter: ^8.8.1
  rxdart: ^0.27.0
  http: ^0.13.0
  flutter_cache_manager: ^3.1.2
  cached_network_image: ^3.1.0
  shared_preferences: ^0.5.7+3
  carousel_slider: ^3.0.0
  firebase_core: ^1.4.0
  flutter_facebook_auth: ^0.3.3
  google_sign_in: ^4.5.1
  firebase_auth: ^3.0.1
  provider: ^4.1.3
  fluttertoast: ^4.0.1
  animate_do: ^1.7.2
  sliding_up_panel: ^1.0.2
  google_maps_flutter: ^2.0.6
  geolocator: ^5.3.2+2
  location: ^4.3.0
  pull_to_refresh: ^1.6.4
  date_picker_timeline: ^1.2.1
  photo_view: ^0.9.2
  #intl: ^0.16.1
  timeline_tile: ^0.1.0
  google_fonts: ^2.0.0
  firebase_messaging: ^10.0.4
  apple_sign_in: ^0.1.0
  flutter_secure_storage: ^3.2.1+1
  flutter_local_notifications: ^8.1.1+1
  webview_flutter: ^1.0.3
  flutter_ticket_widget: ^0.0.1
  page_view_indicators: ^1.3.2
  url_launcher: ^6.0.9
  flutter_form_builder: ^6.0.1
  flutter_bloc: ^6.0.1
  assets_audio_player: ^3.0.3+6
  chips_choice: ^2.0.1
  screenshot: ^1.2.3
  share: ^2.0.1
  image_gallery_saver: ^1.6.7
  flutter_rating_bar: ^3.2.0+1
  nuts_activity_indicator: ^0.1.1
  keyboard_actions: "^3.3.1+1"
  flutter_svg: ^0.22.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_enchilada.png"
  adaptive_icon_background: "assets/icon/logo_enchilada.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/delivery/
    - assets/audio/
    - assets/numeros/
  
  